### ISSUE TITLE
How is node-red-contrib-bigmongo going to be different from node-red-contrib-mongodb2?

### ISSUE THREAD

**Issue by ozomer** [Jacques44/node-red-contrib-bigmongo#1]
Hi,
I noticed that you copied our code from node-red-contrib-mongodb2?
Are you making some special-use fork?

Just curious,
Oren

**Comment by Jacques44** [comment]
Hello!

I'm building a set of nodes for my project I called "big" (bigfile, bigcsv, bigfixed, bigssh, etc.) I'm using a lot MongoDB in my flows and found your work very useful. Great job the parallelism management !

That was not enough for me as I need to 
* Be able to continue a flow when the job is done (this is one of the main design pattern for my big nodes ie a second output with start/end control messages ).
* Be able to use cursor methods (for example to get the last entry, it' better to do a find().sort().limit(1))
* Add support for { $date } as mongoimport in order to transform incoming json date into javascript date
* I like to have visual informations on the nodes (running, error, comlpete)
*  Be able to ignore a list of error codes as I use a lot unique indexes in order to manage retries

I often ask for pull requests but in the case of mongodb2, it's a big change...

Regards
J.

**Comment by ozomer** [comment]
OK,
Good luck with your features.
It's good to know my code is being reviewed :smiley: 
Let me know if you find any bugs.
I developed the parallelism-limit feature after noticing very high loads on our mongodb.
Eventually the problem happened because the responses of some operations contain a reference to the connection object. When Node-RED clones such output message, it clones the connection too - and then all hell breaks loose...
Be careful when you output special objects like cursors etc.
One hack to overcome this problem is to set: `msg.special = function() { return special; }` instead of setting `msg.special = special`. This way the cloning mechanism will not clone `special`, but keep a "reference" to it via the `msg.special()` function.

Regards,
Oren
